# Generated by Django 5.1.6 on 2025-03-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_items', models.CharField(max_length=256)),
                ('total_price', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('forming', 'forming'), ('accepted', 'accepted'), ('waiting_for_accept', 'waiting for accept')], max_length=18)),
            ],
        ),
    ]
